Timer Reset Warning (#9)
kat066/biglunchbox-pomodoro pull request #31
Opened 2022-05-16 10:16 UTC by Burniee

==Changelog==
- Added warning message to setting popup

==Testing==
- Jest and Cypress tests pass

==Version Compatibility==
- Full Compatibility

==Detail Description==
- Updated setting popup menu to reflect when

2022-05-17 14:44 UTC, Burniee commented
Linting fail is from code did I did not work on

2022-05-17 14:46 UTC, Burniee commented
![d3069df8eec641efc9815084165656d5](https://user-images.githubusercontent.com/52307044/168839881-0eeae704-1311-4c4c-9298-938c72de7cfa.png)

2022-05-18 19:51 UTC, kat066 commented
Lgtm, but can you wait until I merged mine? I am finishing up my refactoring, and this might require some change.

2022-05-19 02:20 UTC, Burniee commented
Yeah, that's fine, that's what I initially wanted to do, but it seemed you were taking a while. But yeah, that's chill

2022-05-19 02:25 UTC, zianlin submitted a review, later dismissed
Changes look good, I don’t see anything wrong 👍

2022-05-19 02:26 UTC, kat066 commented
Thanks.

On Wed, May 18, 2022 at 7:21 PM Burniee ***@***.***> wrote:

> Yeah, that's fine, that's what I initially wanted to do, but it seemed you
> were taking a while. But yeah, that's chill
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kat066_biglunchbox-2Dpomodoro_pull_31-23issuecomment-2D1131021273&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=4INAOg3MLiOYIcWpz1u6RQ&m=9Ivz-qnqjulu0z6jjRSdAhtTpMy4KuiGYlAJZTbkzEoKu6by3OhbHUnV-hqmjU8Z&s=DXhr8vn43xdjhsp_9x49HE4aqVT_eyOZ5C6EU5rudfY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APCI2RUBKD26PWYOF33RKI3VKWQQ3ANCNFSM5WA7DTBQ&d=DwMCaQ&c=-35OiAkTchMrZOngvJPOeA&r=4INAOg3MLiOYIcWpz1u6RQ&m=9Ivz-qnqjulu0z6jjRSdAhtTpMy4KuiGYlAJZTbkzEoKu6by3OhbHUnV-hqmjU8Z&s=b_IOq9_i8wcnecjtgh2rEw2EYynepaiSL-duSaJOXBE&e=>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-05-19 18:58 UTC, broiyn commented
also dont forget to fix the linting failure before merging

2022-05-19 19:12 UTC, Burniee commented
Yeah, it's already been fixed, need to wait for Kai's changes to be pushed

2022-05-20 20:26 UTC, kat066 commented
Actual changes lgtm. But your commit also deletes the video and modifies package.json.

2022-05-20 22:41 UTC, kat066 requested changes
Actual changes lgtm. But your commit also deletes the video and modifies package.json and commit message template.

2022-05-20 22:41 UTC, kat066 commented on .gitmessage.txt
>  One line description of your change
This is a commit message template, not the actual commit message, please do not modify. Simply run `git config --global commit.template .gitmessage.txt` to activate the template, and when you do git commit, this will show up, then you can modify there.

2022-05-24 22:12 UTC, closed without merging