Consistent responsive ui
kat066/biglunchbox-pomodoro pull request #64
Opened 2022-06-02 19:29 UTC by Totay

==Changelog==
- made add task, reset, and help responsive
- all pop up menus now have a consistent padding and width scheme
- layout more consistent with original design

==Testing==
- Skips 'start the timer while adding the task' integration test due to weird userflow and known issue for future development.

==Version Compatibility==

==Detail Description==
- the layout does not have a huge gap anymore
- pop ups now follow a max width of 600px and padding of 20px
- pop now have rounded corners
- no more vh and vw values for fonts and nice margin and padding values

2022-06-03 00:23 UTC, kat066 commented
Can you add some screenshots to the pull request description? If you can add a before and after screenshot that would be great! (ex. the one shown in presentation today)

2022-06-03 09:03 UTC, kat066 commented
![Screenshot 2022-06-03 020138](https://user-images.githubusercontent.com/63212870/171824013-e3655bf5-baad-4ffd-8f2b-c8a566808060.png)

2022-06-03 09:06 UTC, kat066 approved these changes, later dismissed
![Screenshot 2022-06-03 020138](https://user-images.githubusercontent.com/63212870/171824391-83955c59-0abb-4c86-8eb8-4ea3d37c291e.png)
Window with small height and large width results in this. Nothing should break in any dimension, because user might adjust the window to any possible dimension so that they can see both what they are working on and the timer. Since we have time constraint, approve and open an issue regarding this.

2022-06-03 09:26 UTC, AxiosDeminence requested changes
Remove id from main and instead just use main tag selectors for css and js. Update files in html_fragments with the present changes in index.html. Other than that, lgtm.

2022-06-03 09:26 UTC, AxiosDeminence commented on source/src/index.html
> -            margin-left: 1.875vw;
Make sure to update the html fragments directory with the same edits done to index.html.

2022-06-03 09:26 UTC, AxiosDeminence commented on source/src/scripts/FocusMode.js
> +        document.getElementById('main').style.display = 'block';
Instead of document.getElementById('main') consider removing the id from main and using document.querySelector('main'). Redundant otherwise.

2022-06-04 03:02 UTC, brooksniu approved these changes, later dismissed
New UI looks cleannnn

2022-06-04 20:51 UTC, AxiosDeminence requested changes

2022-06-04 20:51 UTC, Juhmer-Tena commented on source/src/index.html
> +        <main id="main">
Still have main id="main" in index.html + tests and getElementById in Timer.js and script.js.

2022-06-04 20:51 UTC, Juhmer-Tena commented on source/src/index.html
> +        <img src="icons/focus.svg" alt="" title="Focus on this task" class="focus-icon">
Do NOT revert the resource bundling.

2022-06-04 20:51 UTC, Juhmer-Tena commented on source/src/index.html
> +                <div class="empty-space-border">
Is it possible to just apply padding or extra margin to either the timer-btns element or timer-display element instead?

2022-06-04 21:06 UTC, AxiosDeminence approved these changes

2022-06-04 21:09 UTC, broiyn approved these changes

2022-06-04 21:13 UTC, merged